on: push

jobs:
  build:
    name: Build SimulIDE
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        if: ${{ matrix.os == 'windows-latest'}}
        with:
          install: >-
            make
            git
            mingw-w64-ucrt-x86_64-toolchain
            mingw-w64-ucrt-x86_64-qt5-base
            mingw-w64-ucrt-x86_64-qt5-svg
            mingw-w64-ucrt-x86_64-qt5-tools
            mingw-w64-ucrt-x86_64-qt5-multimedia
            mingw-w64-ucrt-x86_64-qt5-serialport
          msystem: UCRT64
      - name: List DLLs
        run: ls /ucrt64/bin/*.dll
      # - name: Build SimulIDE
      #   working-directory: build_XX
      #   run: |
      #     qmake
      #     make -j 4
      #     windeployqt executables/SimulIDE_*
      #   shell: msys2 {0}
      #   if: ${{ matrix.os == 'windows-latest'}}
      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: SimulIDE
          path: build_XX/executables
