on: push

jobs:
  build:
    name: Build SimulIDE
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: "5.15.2"
      - name: Build SimulIDE
        working-directory: build_XX
        run: |
          qmake
          make
      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: SimulIDE
          path: build_XX/executables
